<?php

$profils = [
    0 => [
        "lastName" => "Dupont",
        "firstName" => "Jean",
        "age" => "34",
        "gender" => "Homme",
        "email" => "dupont-jean@outlook.fr",
        "postalCode" => 75000,
        "picture" => "assets/img/Dupont.jpg",
        "description" => "Je suis un homme qui aime voyager et faire découvrir de nouvelles choses. J'ai hâte de faire votre rencontre."
    ],
    1 => [
        "lastName" => "Doe",
        "firstName" => "John",
        "age" => "25",
        "gender" => "Homme",
        "email" => "john-doe@outlook.fr",
        "postalCode" => 34200,
        "picture" => "assets/img/Doe.jpg",
        "description" => "Je viens de terminer mes études de médecine et je peux donc aujourd'hui me consacrer à ma vie amoureuse."
    ],
    2 => [
        "lastName" => "Paris",
        "firstName" => "Damien",
        "age" => "33",
        "gender" => "Homme",
        "email" => "damien-paris@hotmail.fr",
        "postalCode" => 69300,
        "picture" => "assets/img/Paris.jpg",
        "description" => "Je cherche l'amour avec un grand A. Je compte sur le site Vénus pour trouver ma moitié."
    ],
    3 => [
        "lastName" => "Paul",
        "firstName" => "Henry",
        "age" => "56",
        "gender" => "Homme",
        "email" => "paul-henry@outlook.fr",
        "postalCode" => 22400,
        "picture" => "assets/img/Paul.jpg",
        "description" => "Après 30 ans de mariage, je me remets en selle et j'attends aujourd'hui mon prochain amour qui partagera le reste de ma vie."
    ],
    5 => [
        "lastName" => "Macron",
        "firstName" => "Emmanuel",
        "age" => "43",
        "gender" => "Homme",
        "email" => "manu-president@elysee.com",
        "postalCode" => 75008,
        "picture" => "assets/img/Macron.jpg",
        "description" => "Après de gros soucis sentimentaux avec mon ex-épouse et professionnel, je tente une réinsertion progressive vers une vie normale."
    ],
    6 => [
        "lastName" => "Ferrand",
        "firstName" => "Xavier",
        "age" => "37",
        "gender" => "Homme",
        "email" => "xavier-ferrand@outlook.fr",
        "postalCode" => 88000,
        "picture" => "assets/img/Ferrand.jpg",
        "description" => "Passionné de théâtre, cinéma et sorties culturelles, je souhaite trouver l'autre moitié de mon intellect et de mon coeur."
    ],
    7 => [
        "lastName" => "Anderson",
        "firstName" => "Julia",
        "age" => "26",
        "gender" => "Femme",
        "email" => "juju-anders@hotmail.fr",
        "postalCode" => 75500,
        "picture" => "assets/img/Anderson.jpg",
        "description" => "Jeune et fougueuse, je ne souhaite pas rencontrer ma future moitié mais pourquoi pas celui qui me fera vibrer à nouveau.",
    ],
    8 => [
        "lastName" => "Pavot",
        "firstName" => "Suzy",
        "age" => "45",
        "gender" => "Femme",
        "email" => "suzy-pavot@outlook.fr",
        "postalCode" => 69000,
        "picture" => "assets/img/Pavot.jpg",
        "description" => "Je souhaite pouvoir enfin rencontrer l'amour.",
    ],
    9 => [
        "lastName" => "Roberts",
        "firstName" => "Pamela",
        "age" => "31",
        "gender" => "Femme",
        "email" => "pam-robs@outlook.fr",
        "postalCode" => 13000,
        "picture" => "assets/img/Roberts.jpg",
        "description" => "Après avoir consacré ma vie à mon travail, j'aimerais pouvoir trouver l'amour et enfin fonder une famille.",
    ],
    10 => [
        "lastName" => "Martin",
        "firstName" => "Audrey",
        "age" => "30",
        "gender" => "Femme",
        "email" => "suzy-pavot@outlook.fr",
        "postalCode" => 69000,
        "picture" => "assets/img/Martin.jpg",
        "description" => "Je souhaite pouvoir enfin rencontrer l'amour.",
    ],
    11 => [
        "lastName" => "Varot",
        "firstName" => "Luna",
        "age" => "19",
        "gender" => "Femme",
        "email" => "luna-varot@hotmail.fr",
        "postalCode" => 37000,
        "picture" => "assets/img/varot.jpg",
        "description" => "J'aimerais faire de belles rencontres et partager un bout de chemin avec celui qui fera chavirer mon coeur.",
    ],
    12 => [
        "lastName" => "Trogneux",
        "firstName" => "Brigitte",
        "age" => "63",
        "gender" => "Femme",
        "email" => "brigitte-trogneux@outlook.fr",
        "postalCode" => 75016,
        "picture" => "assets/img/trogneux.jpeg",
        "description" => "Séparée depuis peu, je cherche un nouveau petit jeune",
    ],
];
